version: '2'
services:
  thinkit-app:
    image: thinkit
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://thinkit-mssql:1433;database=ThinkIt
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  thinkit-mssql:
    extends:
      file: mssql.yml
      service: thinkit-mssql
